# Generated by Django 2.2 on 2019-05-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='child_comment',
        ),
    ]
