# Generated by Django 2.2 on 2019-05-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0004_auto_20190502_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_post', to='newspost.Post'),
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
