# Generated by Django 2.2 on 2019-05-05 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newspost', '0006_auto_20190504_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_upvote',
            field=models.ManyToManyField(related_name='comment_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='post_upvote',
            field=models.ManyToManyField(related_name='post_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
