# Generated by Django 2.2 on 2019-05-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspost', '0010_auto_20190506_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote_comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='upvote_comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='upvote_post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='upvote_post',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='path',
        ),
        migrations.DeleteModel(
            name='RecursiveThing',
        ),
        migrations.DeleteModel(
            name='Upvote_Comment',
        ),
        migrations.DeleteModel(
            name='Upvote_Post',
        ),
    ]
